### ISSUE TITLE
How can I help and contribute? (Didn’t know where else to contact)

### ISSUE THREAD

**Issue by ryan-parag** [code-for-tb/tampa-adopt-a-drain#4]
Hello!

I came across the “Code for America” chapter from a slack group and was wondering if/how I could help out by providing some UI/UX design support on this project.

If so, I’d love to contribute: Parag.ryan@gmail.com

**Comment by fplaras** [comment]
Hi @ryan-parag are you interested in joining code for tampa bay and helping out or just this project in particular?

**Comment by ryan-parag** [comment]
Hey @fplaras ! I would definitely be interested in helping out with "Code for Tampa Bay" - just didn't know how to go about that. I saw the project had a listing for some UI/UX design support:
![image](https://user-images.githubusercontent.com/22060683/81991059-67004180-960e-11ea-8b67-a1634fbfc070.png)
and wondered if you all still needed some help in that area.

**Comment by fplaras** [comment]
@ryan-parag some of the stack has changed but anyone is welcome to help even if its just recommendations for improvement. I will send you an invite to our slack channel with the latest updates and standup meetings.

**Comment by fplaras** [comment]
@ryan-parag I have added you to the slack channel and look forward to speaking with you on future development and changes you might recommend. Closing issue.
